# Neural Network Architecture

A **neural network architecture** refers to the *structure or layout of a neural network*. It defines how the individual nodes or layers are organized and connected to each other. The architecture *determines how the network processes and transforms input data to produce output predictions or classifications*.

## Input Data

*To understand the purpose of the input layer in the whole architecture of our neural networks, it is important that we gain an understanding to the common concepts described below:*

### Basic Terms

**Magnitude** is defined as the *measurement of quantity or value of a specific feature*. For example, scalar ***x = 10*** represents a measurement of the speed of a sample.

**Direction** definition is *PENDING*

### Data Structure

*Neural networks input data are based from linear algebra concepts of data structures, such as **scalars**, **vectors**, **matrices**, and **tensors**. All data structures will be explained here in concise detail.*

In [4]:
# Import relevant Python libraries to assist learning and understanding datasets with Python
import numpy as np

#### Scalars

**Scalars** are *single numbers* and are an example of a *0th-order tensor*. In machine learning, scalars can only represent *magnitude but NOT direction*. They could either be ***real numbers, integers, or rational numbers***. An example of scalars, both mathematically and programatically are shown below:


*Scalar Mathematic Examples*:
* x = 1
* y = 2
* z = 3

In [3]:
## Scalar Programmatical Examples in Python:
scalar_one = np.array(1)
scalar_two = np.array(2)
scalar_three = np.array(3)

print(f"Scalar examples in Python are {scalar_one}, {scalar_two}, and {scalar_three}.")

Scalar examples in Python are 1, 2, and 3.


#### Vectors

**Vectors** are *1st - dimensional ordered array of scalars and are examples of 1st-order tensors*. They have both *magnitude* and *direction*. They hold *sequence of values* for either the *feature or sample*. In mathematics, a vector can be oriented either in a horizontal or vertical manner. On the other hand in machine learning, a *vector's orientation* defines whether it is a data structure *storing values for our features or sample*. For ***horizontal vectors***, they represent *sample data*, while ***vertical vectors*** represent *feature data*. Examples of vectors, both mathematical and programatical concepts, are shown below:

In [6]:
# Vector Mathematical Examples:
# x = [1,2,3,4,5]
# y = [3
#      5        
#      [7 

In [20]:
# Vectors in Machine Learning (PYTHON)

# Features
age = np.array([10,15,20])
year = np.array([11,16,21])
print(f"Values in age feature vector are {age}")
print(f"Values in year feature vector are {year}")

# Samples
sample_one = np.array([age[0], year[0]])
sample_two = np.array([age[1], year[1]])
sample_three = np.array([age[2], year[2]])
print(f"\nValues in first sample vector, from age to year, are {sample_one}")
print(f"Values in second sample vector, from age to year, are {sample_two}")
print(f"Values in third sample vector, from age to year, are {sample_three}")

Values in age feature vector are [10 15 20]
Values in year feature vector are [11 16 21]

Values in first sample vector, from age to year, are [10 11]
Values in second sample vector, from age to year, are [15 16]
Values in third sample vector, from age to year, are [20 21]


#### Matrix

**Matrix** are *2nd - dimensional ordered array of scalars* and are *examples of 2st-order tensors*. They have both *magnitude* and *direction*. They hold *vectors arranged in rows and columns*. Each element in a matrix is identified by *two indices: row and column*. You can compare a matrix to a *table of data*, with *either rows and columns representing either the dataset's features or sample depending in how you instantiated it programmatically*. Matrices are used to *represent linear transformations*, *systems of equations*, or *multi-dimensional data*. Examples of matrices, both mathematical and programatical concepts, are shown below:

In [14]:
# Matrix Mathematical Examples:

# x = [1, 2, 3
#      3, 4, 5]

# y = [3, 4, 5
#      5, 6, 7]

In [22]:
# Matrices in Machine Learning (PYTHON)

# Features
matrix_one = np.array([age, year])
matrix_two = np.array([sample_one, sample_two, sample_three])

print(f"Values in first matrix created by combining vectors for features are shown below: \n{matrix_one}")
print(f"\nValues in second matrix created by combining vectors for samples are shown below: \n{matrix_two}")

Values in first matrix created by combining vectors for features are shown below: 
[[10 15 20]
 [11 16 21]]

Values in second matrix created by combining vectors for samples are shown below: 
[[10 11]
 [15 16]
 [20 21]]


*Note the difference between the outputs despite the fact that the vectors of both features and samples represent a singular dataset*. The **first matrix output** shows an *array, wherein each column represents samples and each rows represents features*. The **second matrix output** shows the *opposite of the first matrix*. **This is a very important thing to note for future use**